name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - run: yarn test
